@CharacterVaulBack_HostAddress = http://localhost:5164

POST {{CharacterVaulBack_HostAddress}}/Auth/login/
Accept: application/json

###

POST {{CharacterVaulBack_HostAddress}}/User/add/
Content-Type: application/json

{
  "Username": "kakauli",
  "Password": "samantavoltapramim",
  "Email": "mmmmm@yes"
}

###

POST {{CharacterVaulBack_HostAddress}}/Sheet/sheet/
Content-Type: application/json

{
    "UserId": 8,
    "Name": "louro",
    "Race": "louro",
    "Origin": "louroland",
    "Class": "louro",
    "Level": 1,
    "HP": 2,
    "MP": 100
}

###

POST {{CharacterVaulBack_HostAddress}}/Skill/skill/
Content-Type: application/json

{
  "Name": "loirar",
  "Source": "blonde blonde",
  "SheetId": 6
}