@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwianRpIjoiMzFjMzVmNzAtNjcxMC00N2Q4LTg4MGYtODQwNzg5YTNiZTMxIiwibmJmIjoxNzQwMjI5MjU2LCJleHAiOjE3NDAzMTU2NTYsImlhdCI6MTc0MDIyOTI1NiwiaXNzIjoiQ2hhcmFjdGVyVmF1bHRCYWNrIiwiYXVkIjoiQ2hhcmFjdGVyVmF1bHRGcm9udCJ9.LiLu5oOQ6vTtLg95A5QWK77l12GhtbaTgy_9bNrY5ng
@CharacterVaulBack_HostAddress = http://localhost:5164

POST {{CharacterVaulBack_HostAddress}}/Auth/login/
Accept: application/json

###

POST {{CharacterVaulBack_HostAddress}}/User/users/
Content-Type: application/json

{
  "Username": "dor",
  "Password": "p",
  "Email": "m@m.M"
}

###

POST {{CharacterVaulBack_HostAddress}}/{{token}}/Sheet/sheets/
Content-Type: application/json

{
    "UserId": 4,
    "Name": "louro",
    "Race": "louro",
    "Origin": "louroland",
    "Level": 1,
    "HP": 2,
    "MP": 100
} 

###

POST {{CharacterVaulBack_HostAddress}}/Skill/skills/
Content-Type: application/json
Authorization:Bearer <token>

{
  "Name": "loirar",
  "Source": "blonde blonde",
  "SheetId": 1
}

###

DELETE {{CharacterVaulBack_HostAddress}}/{{token}}/Sheet/delete
Content-Type: application/json

{
  "SheetId": 3,
  "UserId": 4
}


###

DELETE {{CharacterVaulBack_HostAddress}}/Skill/delete
Content-Type: application/json

###

DELETE {{CharacterVaulBack_HostAddress}}/User/delete
Content-Type: application/json

###

PATCH {{CharacterVaulBack_HostAddress}}/Skill/update
Content-Type: application/json

{
  "Source": "teeeeeeeeeeeee",
  "SkillId": 1,
  "SheetId": 1
}

###

PATCH {{CharacterVaulBack_HostAddress}}/Sheet/update
Content-Type: application/json

{
  "Class": "<X>",
  "UserId": 1,
  "SheetId": 2
}

### 

POST {{CharacterVaulBack_HostAddress}}/Auth/login
Content-Type: application/json

{
  "Email": "1",
  "Password": "1"
}

